### ISSUE TITLE
All python hosts failing during test stage

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotFramework-FunctionalTests#128] opened 2020-09-09 00:18 UTC
Failures started on Friday 9/4.
Pipelines failing: Python hosts:
![image](https://user-images.githubusercontent.com/44449640/92539755-4c725980-f1f7-11ea-9b33-5d95878a9996.png)

Deployment completes without errors. Below is a sample output of the test failure:

`
2020-09-04T10:22:25.2815177Z Starting test execution, please wait...
2020-09-04T10:22:25.8373485Z 
2020-09-04T10:22:25.8375087Z A total of 1 test files matched the specified pattern.
2020-09-04T10:23:15.1514642Z   X Skill_OAuthCard_SignInSuccessful [41s 648ms]
2020-09-04T10:23:15.1516045Z   Error Message:
2020-09-04T10:23:15.1516988Z    Assert.IsTrue failed. Expected: Echo: skill
2020-09-04T10:23:15.1517798Z   Stack Trace:
2020-09-04T10:23:15.1518932Z      at SkillFunctionalTests.Bot.TestBotClient.AssertReplyAsync(String expected, CancellationToken cancellationToken) in D:\a\1\s\SkillsFunctionalTests\tests\SkillFunctionalTests\Bot\TestBotClient.cs:line 148
2020-09-04T10:23:15.1521826Z    at FunctionalTests.OAuthSkillTest.Skill_OAuthCard_SignInSuccessful() in D:\a\1\s\SkillsFunctionalTests\tests\SkillFunctionalTests\OAuthSkillTest.cs:line 37
2020-09-04T10:23:15.1522676Z 
2020-09-04T10:23:15.1523429Z   Standard Output Messages:
2020-09-04T10:23:15.1524162Z  Sent to bot: Hello
2020-09-04T10:23:15.1524895Z  Messages sent from bot:
2020-09-04T10:23:15.1525655Z  Type:message; Text:Hello and welcome!
2020-09-04T10:23:15.1526498Z  Type:message; Text:Me no nothin'. Say "skill" and I'll patch you through
2020-09-04T10:23:15.1527403Z  Type:message; Text:Me no nothin'. Say "skill" and I'll patch you through
2020-09-04T10:23:15.1528396Z  Sent to bot: skill
2020-09-04T10:23:15.1528845Z  Messages sent from bot:
2020-09-04T10:23:15.1529296Z  Type:message; Text:Got it, connecting you to the skill...
2020-09-04T10:23:15.1529802Z  Type:message; Text:The skill encountered an error or bug.
2020-09-04T10:23:15.1530337Z  Type:message; Text:To continue to run this bot, please fix the bot source code.
2020-09-04T10:23:15.1530880Z  Type:message; Text:The skill encountered an error or bug.
2020-09-04T10:23:15.1531606Z  Type:message; Text:To continue to run this bot, please fix the bot source code.
`

**Comment by denscollo** [comment] 2020-09-14 13:41
Hi @mrivera-ms, we identified the cause of this issue to be related to the two latest python BotBuilder package versions (4.11.0.20200909.dev164711 and 4.11.0.20200904.dev163701). Previous versions work according to expectations.
This error is being introduced in the BotBuilder-Python's [#1375](https://github.com/microsoft/botbuilder-python/pull/1375).
We suggest to open a new issue in BotBuilder Python and close this one, let us know if you want us to create it.

**Closed** 2020-09-14 20:14 UTC
